import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavBarComponent  from "../navbar/NavBarComponent";
import "./globals.css";
import person from "../assets/person.svg";
import gift from "../assets/gift.svg";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-start">
        <NavBarComponent item={{
          dashboardTitle: "Dashboard",
          items:[
            {
              title:"Users",
              link:"/users",
              icon:person,
              
            },
            {
              title:"Gift",
              link:"/gift",
              icon:gift,
            }
          ]
        }} />
        {children}
        </div>
      </body>
    </html>
  );
}
