import type { Metadata } from "next";

import SideNavComponent from "@/navbar/SubNavComponent";
import { RoutesName } from "@/lib/constant";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-row w-full">
      <SideNavComponent
        item={{
          dashboardTitle: "Dashboard",
          items: [
            {
              title: "Active Users",
              link: RoutesName.ACTIVE_USERS,
            },
            {
              title: "Blocked Users",
              link: RoutesName.BLOCKED_USERS,
            },
          ],
        }}
      />



      {children}
  
    </div>
  );
}
